# Generated by Django 4.1.7 on 2023-04-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=25)),
                ('precio_producto', models.IntegerField()),
                ('vencimiento_producto', models.DateField()),
                ('descripcion_producto', models.CharField(max_length=60)),
            ],
        ),
    ]
